apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: gpt-4-1
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: gpt-4.1
  policies:
    auth:
      secretRef:
        name: openai-secret
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: gpt-5-mini
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: gpt-5-mini
  policies:
    auth:
      secretRef:
        name: openai-secret
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: gpt-4-1-mini
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: gpt-4.1-mini
  policies:
    auth:
      secretRef:
        name: openai-secret
