apiVersion: edgecloudlabs.edgecloudlabs.com/v1alpha1
kind: LLMBackend
metadata:
  name: gpt-4-1-backend
  namespace: default
spec:
  apiKeySecretRef:
    name: openai-secret
  deployment: remote
  model: gpt-4.1
status:
  phase: Evaluated
  results:
    avgResponseTime: "5.0000"
    tokensPerSecond: "40.00"
    overallAccuracy: "0.7821"
    categoryAccuracy:
      biology: "0.8500"
      business: "0.9500"
      chemistry: "0.8000"
      computer science: "0.7000"
      economics: "0.9000"
      engineering: "0.6500"
      health: "0.8000"
      history: "0.9000"
      law: "0.8500"
      math: "0.7500"
      other: "0.6000"
      philosophy: "0.7000"
      physics: "0.7500"
      psychology: "0.7500"
    pricing:
      prompt: "5.00"
      completion: "15.00"
---
apiVersion: edgecloudlabs.edgecloudlabs.com/v1alpha1
kind: LLMBackend
metadata:
  name: gpt-5-mini-backend
  namespace: default
spec:
  apiKeySecretRef:
    name: openai-secret
  deployment: remote
  model: gpt-5-mini
status:
  phase: Evaluated
  results:
    avgResponseTime: "0.5000"
    tokensPerSecond: "180.00"
    overallAccuracy: "0.6607"
    categoryAccuracy:
      biology: "0.9000"
      business: "0.5000"
      chemistry: "0.9500"
      computer science: "0.5500"
      economics: "0.5000"
      engineering: "0.5000"
      health: "0.6000"
      history: "0.5500"
      law: "0.5000"
      math: "0.9500"
      other: "0.6500"
      philosophy: "0.5500"
      physics: "0.9500"
      psychology: "0.5500"
    pricing:
      prompt: "3.00"
      completion: "10.00"
---
apiVersion: edgecloudlabs.edgecloudlabs.com/v1alpha1
kind: LLMBackend
metadata:
  name: gpt-4-1-mini-backend
  namespace: default
spec:
  apiKeySecretRef:
    name: openai-secret
  deployment: remote
  model: gpt-4.1-mini
status:
  phase: Evaluated
  results:
    avgResponseTime: "2.0000"
    tokensPerSecond: "90.00"
    overallAccuracy: "0.5536"
    categoryAccuracy:
      biology: "0.4000"
      business: "0.3500"
      chemistry: "0.3500"
      computer science: "0.9500"
      economics: "0.3000"
      engineering: "0.9000"
      health: "0.4000"
      history: "0.3500"
      law: "0.3000"
      math: "0.5000"
      other: "0.5000"
      philosophy: "0.4000"
      physics: "0.4500"
      psychology: "0.4000"
    pricing:
      prompt: "0.50"
      completion: "1.50"
