apiVersion: edgecloudlabs.edgecloudlabs.com/v1alpha1
kind: LLMBackend
metadata:
  name: gpt-oss-120b-local
  namespace: intelligent-router-system
spec:
  deployment: local
  model: gpt-oss-120b
  endpoint: http://10.95.161.240.nip.io:8000/v1
  #apiKeySecretRef:
  #  name: model-api-key