apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-service-monitor
  namespace: vllm 
spec:
  endpoints:
  - interval: 5s
    port: api
    scheme: http
    path: /metrics
  selector: 
    matchLabels:
      app: vllm