apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: sp-electricity-cost-agent
  namespace: kagent
spec:
  description: Assistant that can check electricity costs in Spain
  type: Declarative
  declarative:
    modelConfig: default-model-config
    stream: true
    systemMessage: |
      Instructions:
      * Use the 'spain-electricity-cost-mcp' to answer questions about power pricing.
      * Never expose internal reasoning.
      * Never describe tool planning.
      * Only return the final structured answer.

      Output:
      * The response MUST be in json. 
        * For electricity: Example: '{ "price": "0.007"}'
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: MCPServer
        name: spain-electricity-cost-mcp
        namespace: kagent
        toolNames:
        - get_current_price
      type: McpServer