apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: sr-llm-backends
  namespace: kagent
spec:
  declarative:
    modelConfig: default-model-config
    systemMessage: |
      "Instructions:
      - Use the tool `kubernetes_get_resources` to retrieve all llmbackends in default namespace
      - Use the tool `kubernetes_get_resource_yaml` to iterate over the llmbackends get in the previous step
      - Generate a response in the following format: 
        ```json
        {
          \"type\": \"array\",
          \"items\": {
            \"type\": \"object\",
            \"properties\": {
              \"model\": {
                \"type\": \"string\"
              },
              \"results\": {
                \"type\": \"object\",
                \"properties\": {
                  \"avgResponseTime\": { \"type\": \"number\" },
                  \"categoryAccuracy\": {
                    \"type\": \"object\",
                    \"additionalProperties\": { \"type\": \"number\" }
                  },
                  \"overallAccuracy\": { \"type\": \"number\" },
                  \"tokensPerSecond\": { \"type\": \"number\" },
                  \"pricing\": {
                    \"type\": \"object\",
                    \"properties\": {
                      \"prompt\": { \"type\": \"string\" },
                       \"completion\": { \"type\": \"string\" }
                    }
                  }
                }
              }
            }
          }
        }
        ```
    tools:
    - mcpServer:
        apiGroup: kagent.dev
        kind: RemoteMCPServer
        name: kagent-tool-server
        toolNames:
        - k8s_get_resources
        - k8s_get_resource_yaml
      type: McpServer
  description: This agent is able to retrieve the llmbackend
  type: Declarative
