langfuse:
  salt:
    value: secureSalt
  nextauth:
    secret:
      value: "912ae68a7ed2d68f730fbb0929970217a2eca87396e9eb6862803eee0519c860"

postgresql:
  auth:
    # If you want to use `postgres` as the username, you need to provide postgresPassword instead of password.
    username: langfuse
    password: "langfuse"

clickhouse:
  auth:
    password: "clickhouse"
